### ISSUE TITLE
Release pelican-webassets v2.0.0 on PyPI

### ISSUE THREAD

**Issue by kdeldycke** [pelican-plugins/webassets#2]
This is a ticket to keep track of the packaging and PyPi distribution of the next 2.0.0 version:

* [x] Move legacy plugin from monorepo.
* [x] Re-package plugin. Done at https://github.com/pelican-plugins/webassets/pull/1 .
* [x] Let @bryanbrattlof merge back his changes from https://git.bryanbrattlof.com/pelican-webassets . Done at https://github.com/pelican-plugins/webassets/pull/4 .
* [x] Setup CI/CD by the way of GitHub workflows.
* [x] Add [`pelicanteam`](https://pypi.org/user/pelicanteam/) to [`pelican-webassets` on PyPi](https://pypi.org/project/pelican-webassets/).
* [x] Release next v2.0.0 on PyPI.
* [x] Flag the plugin as migrated by merging https://github.com/getpelican/pelican-plugins/pull/1313

**Comment by kdeldycke** [comment]
@justinmayer, any idea under which version number should we release the next one?

**Comment by bryanbrattlof** [comment]
Hi @kdeldycke!

I managed to merge the changes in from `pelican-webassets`currently awaiting review on #4. Both version can work together however what we put in `PLUGINS` has changed for both. the old `assets` and `pelican_webassets` should now be:

```python
PLUGINS = ['webassets']
```

I could add in symbolic links for both, but I'm unsure how well they are supported in a windows environment.

**Comment by kdeldycke** [comment]
@bryanbrattlof I'm ok to not over-think this and only allow for the `webassets` keyword, which is in line with all the naming convention for other plugins. This will lower surprises and expectations about the new scheme for Pelican plugins. And it reduces the number of things we will not have to change in a future release.

Now with #4 in mind, and with `pelican-webassets 1.0.0` already released on PyPi, I propose to have the next release bumped to 2.0.0. We should not be too shy about versions, and the 2.0.0 is a strong signal for users to pay attention to the new format and naming changes.

**Comment by kdeldycke** [comment]
pelican-webassets v2.0.0 is now ready to be released on PyPi thanks to the fantastic work of @bryanbrattlof! 🚀

**Comment by justinmayer** [comment]
Things have been a bit busy around here, but I'll chime in tomorrow. Thanks for all your work and patience!

**Comment by kdeldycke** [comment]
Thanks @justinmayer for the kind update but take your time. There's no hurry: me and @bryanbrattlof can contribute to this repository so there's no blocker. We can happily fix and enhance the code asynchronously and take care of any outstanding issue. I don't want you to burn out because of open-source maintenance. You're too important for this community! 🤗

**Comment by justinmayer** [comment]
Thanks for the kind words. No worries about me burning out. I enjoy the collaboration.

Regarding the version number, I agree that v2.0.0 seems appropriate. 👍

**Comment by bryanbrattlof** [comment]
Hey everyone! I hope you're enjoying your first quarter of 2021.

Is there anything we're missing for the CI/CD pipeline?

**Comment by justinmayer** [comment]
@bryanbrattlof: I'll add the necessary bits by Friday so we can get the next release out. Many thanks for your patience and for following up! 😁

**Comment by justinmayer** [comment]
@bryanbrattlof: In order for the auto-publication to PyPI to function, we'll need to add the `pelicanteam` PyPI account to the [webassets project](https://pypi.org/project/pelican-webassets/) as a collaborator, with type `owner`. Would you please let me know when that's all set so I can continue to the next step? Thank you! 🤖

**Comment by bryanbrattlof** [comment]
Thanks @justinmayer. I just sent the invite

**Comment by justinmayer** [comment]
@bryanbrattlof: Thanks!

@kdeldycke / @bryanbrattlof: By the way, what should we put in the release notes for v2.0? Could you help out by suggesting a list of bullet points for that?

**Comment by bryanbrattlof** [comment]
Thanks @justinmayer!

I'm not 100% on the wording of this so feel free to edit and suggest. From my notes, the biggest changes include:

- We've successfully consolidated development of `assets` and `pelican-webassets` into the new pelican-plugins organization. All future development fun will now be at: https://github.com/pelican-plugins/webassets
- With the consolidation efforts, all `ASSET_*` settings have now been deprecated and replaced with `WEBASSETS_*` to align with the `pip` package naming. All settings for the plugin can be found at: https://github.com/pelican-plugins/webassets#configuration
- Refactored the plugin to take advantage of Pelican's new namespace package system. (https://docs.getpelican.com/en/latest/plugins.html) Allowing Pelican to automatically find and use the plugin after you've installed it with `pip install pelican-webassets`
- Fixed a bug where an empty `THEME_STATIC_DIR` setting would create malformed URL addresses

I think that highlights most of the user facing changes.

**Comment by justinmayer** [comment]
Many thanks for the release summary, Bryan. I just triggered the [v2.0.0 release](https://github.com/pelican-plugins/webassets/releases/tag/2.0.0), which thanks to your and @kdeldycke's assistance is now on PyPI. 🎉
