### ISSUE TITLE
{{ ASSET_URL }} contains unnecessary leading slash

### ISSUE THREAD

**Issue by sagamusix** [pelican-plugins/webassets#3]
Ported from https://github.com/getpelican/pelican-plugins/issues/1018

`{{ ASSET_URL }}` contains a leading slash, which is inconsistent with the provided example usage pattern `{{ SITEURL }}/{{ ASSET_URL }}` that can be found in the readme. This turns into `https://example.org//path/to/asset` instead of the expected `https://example.org/path/to/asset`. Either the examples should be updated to not contain a slash between `{{ SITEURL }}` and `{{ ASSET_URL }}`, or `{{ ASSET_URL }}` should not contain a leading slash, which would be more consistent with the rest of Pelican (but I understand this can be a problem because the variable is provided by the webassets dependency).

**Comment by bryanbrattlof** [comment]
Hi @sagamusix

I'm having trouble reproducing what you're seeing. Do you mind posting what your `SITEURL` `THEME_STATIC_DIR` settings and what `filters` you are using?

**Comment by sagamusix** [comment]
```
SITEURL = 'https://openmpt.org'
THEME_STATIC_DIR = ''
```

I am using cssmin and jsmin filters.

**Comment by bryanbrattlof** [comment]
Thanks for the extra info! I was able to figure out what's going on. :partying_face: 

When we set `THEME_STATIC_DIR = ''` pelican will happily put `''` (nothing) as a folder name when generating the URL, resulting in something like `http://example.com//path/to/asset` complete with a static theme directory named `''`

The confusion comes from how pelican will remove the extra `/` (generating the broken links) when saving the compiled asset file to our final output folder.

~This seems like a bug with how Pelican builds the URLs but I haven't looked into it yet.~

As a workaround until this gets fixed, removing the `/` from the `{{SITEURL}}/{{ASSET_URL}}` part will work.

Hope this help. 
:clinking_glasses:  Cheers!

**Comment by sagamusix** [comment]
> As a workaround until this gets fixed, removing the / from the {{SITEURL}}/{{ASSET_URL}} part will work.

Yup, that's what I'm currently doing. :)

**Comment by bryanbrattlof** [comment]
Whoops! :facepalm:  It's definitely a bug in the plugin. around [line 46](https://github.com/pelican-plugins/webassets/blob/main/pelican/plugins/webassets/webassets.py#L46:L48) in `create_assets_env()`

```python
theme_static_dir = generator.settings["THEME_STATIC_DIR"]
assets_destination = os.path.join(generator.output_path, theme_static_dir)
generator.env.assets_environment = Environment(assets_destination, theme_static_dir)
```
We happily put `''` (nothing) as a folder name when generating the URL.

I'll open a new PR and get this fixed :sweat_smile: 

As a workaround the `{{SITEURL}}/{{ASSET_URL}}` will still work, or you could try using `THEME_STATIC_DIR = './'`

**Comment by sagamusix** [comment]
Sorry for the late reply, but I just tested the PR and it works fine!
